version: "3.9"
services:
  web:
#    image: luannfelipe/koa
    build: back_end
    command: "npx nodemon node back_end/src/server/App.js"
    container_name: server
    depends_on:
      - postgres-compose
    ports:
      - 3000:3000
    volumes:
       - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
      - network
  postgres-compose:
    container_name: postgres
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "banco"
      POSTGRES_PASSWORD: "12345"
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5440:5432"
    networks:
      network:
        aliases:
          - postgresdb
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin1234
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose

  front:
#    container_name: front
    build: front_end
    command: npm run dev
    image: luannfelipe/next
    restart: always
    environment:
      APP_ENV: development
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true