version: "3.9"
services:
  postgres-compose:
    container_name: postgres
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "banco"
      POSTGRES_PASSWORD: "12345"
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5440:5432"
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin1234
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
  web:
    build: back_end
    command: "npx nodemon node back_end/src/server/App.js"
    container_name: koa
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
#  front:
#    container_name: front
#    command: npm run dev
#    build:
#      context: front_end
#      dockerfile: Dockerfile
#    restart: always
#    environment:
#      APP_ENV: development
#    volumes:
#      - ./:/app
#    ports:
#      - "8080:8080"
volumes:
  postgres-data:
    external: true
